#!/bin/bash
# Testing Guide for Tebak Lagu Scoring Fix

echo "========================================"
echo "TEBAK LAGU SCORING FIX - TESTING GUIDE"
echo "========================================"
echo ""

echo "📌 TESTING STEPS:"
echo ""

echo "1️⃣ PREPARATION"
echo "   - Frontend running on http://localhost:5174"
echo "   - Backend API accessible at /api/endpoint"
echo "   - MySQL database tebak_lagu sudah setup"
echo ""

echo "2️⃣ BROWSER CONSOLE MONITORING"
echo "   - Open DevTools (F12) → Console tab"
echo "   - Watch for logs:"
echo "     • '✅ Jawaban BENAR! Score updated: X → Y'"
echo "     • '❌ Jawaban SALAH!'"
echo "     • '🎯 FINISHING QUIZ - Final Score: {...}'"
echo "     • '📊 RESULT PAGE - Scoring Display: {...}'"
echo ""

echo "3️⃣ TEST SCENARIOS"
echo ""

echo "SCENARIO A: 3 Soal (2 Benar, 1 Salah)"
echo "   Expected: Score 2/3, Akurasi 67%, Performance '💪 BAGUS!'"
echo "   Browser Console:"
echo "     • Log1: '✅ Score updated: 0 → 1'"
echo "     • Log2: '✅ Score updated: 1 → 2'"
echo "     • Log3: '❌ Jawaban SALAH!'"
echo "     • Log4: '🎯 FINISHING QUIZ - score: 2, total: 3'"
echo "     • Log5: '📊 RESULT - scoreAkhir: 2, totalSoal: 3, akurasiPercentage: 67'"
echo ""

echo "SCENARIO B: 5 Soal (Semua Benar)"
echo "   Expected: Score 5/5, Akurasi 100%, Performance '🏆 SEMPURNA!'"
echo "   Browser Console:"
echo "     • Log: '✅ Score updated: 0→1, 1→2, 2→3, 3→4, 4→5'"
echo "     • Log: '🎯 FINISHING QUIZ - score: 5, total: 5'"
echo "     • Log: '📊 RESULT - scoreAkhir: 5, totalSoal: 5, akurasiPercentage: 100'"
echo ""

echo "SCENARIO C: 7 Soal (3 Benar, 4 Salah)"
echo "   Expected: Score 3/7, Akurasi 43%, Performance '📚 TERUS BELAJAR!'"
echo "   Browser Console:"
echo "     • Log: '✅ Score updated: 0→1, 1→2, 2→3'"
echo "     • Log: '❌ Jawaban SALAH!' (4 times)"
echo "     • Log: '🎯 FINISHING QUIZ - score: 3, total: 7'"
echo "     • Log: '📊 RESULT - scoreAkhir: 3, totalSoal: 7, akurasiPercentage: 43'"
echo ""

echo "4️⃣ VERIFICATION CHECKLIST"
echo "   ✅ Score display di TebakLagu.jsx matches console log"
echo "   ✅ Result page shows correct scoreAkhir (jumlah benar)"
echo "   ✅ Akurasi % calculated correctly ((benar/total)*100)"
echo "   ✅ Performance rating matches akurasi threshold"
echo "   ✅ Combo/Streak values correct"
echo "   ✅ Score saved to database (leaderboard shows correct score)"
echo ""

echo "5️⃣ DEBUGGING TIPS"
echo "   - If score shows 0: Check scoreRef sync in useEffect"
echo "   - If akurasi wrong: Verify Math.round() formula"
echo "   - If state not passing: Check navigate() state object"
echo "   - If database not updated: Check simpan_hasil.php POST handling"
echo ""

echo "========================================"
echo "Testing completed! Check console logs."
echo "========================================"
